### PR TITLE
Using a regex to find an actual word to translate in context, and not…

### PR DESCRIPTION
**Pull request by mircealungu**
This fixes the glaring problem we have for now (see https://github.com/zeeguu/api/issues/315 in the zeeguu api repo). In the future we should add another utility function here that works with alignments.

### CODE REVIEW

**Review by tfnribeiro — APPROVED** [review]
Looks good!

**Comment by tfnribeiro** [comment]
Why use assertEqual instead assert [Condition], [ErrorMessage] ?

**Comment by mircealungu** [comment]
> Why use assertEqual instead assert [Condition], [ErrorMessage] ?

super good question! I think the old wisdom was that `assertEqual` was returning more informative details on failure. i just tested it and the output seems to be the same, at least when running with `pytest`.

**Comment by mircealungu** [comment]
Do you know what this means @tfnribeiro ? The PR has your approval but merging is still blocked? Why does it say that you approved changes _with r-o permissions_?

image

**Comment by tfnribeiro** [comment]
I always have used assert and in Zeeguu Unit testing we also use assert - that's why I am asking - Good to know it's another way of writing it though! 

Regarding the Read-only, I think it might be because I can't edit this repository?

**Pull request merged**
